download_url: https://galaxy.ansible.com/download/redhatinsights-eda-1.0.0.tar.gz
format_version: 1.0.0
name: eda
namespace: redhatinsights
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.0.0
version_url: https://galaxy.ansible.com/api/v2/collections/redhatinsights/eda/versions/1.0.0/
